url: https://mwfgithub.github.io


# Site settings
title: Muslim Water Fund  
email: info@muslimwaterfund.com
description: "A volunteer based group working towards raising funds for water related projects (i.e., clean drinking water, sanitation systems, etc) in areas of need."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 3663FE
  secondary: 033cfe   
  secondary-dark: 333

# Team names, titles and social links
people:
- name: 
  pic: 
  position: 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: 
  pic: 
  position:
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: 
  pic: 
  position: 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/muslimwaterfund
  - title: facebook
    url: http://facebook.com/muslimwaterfund


# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: 

# Build settings
markdown: kramdown
permalink: pretty